config/routes.rb
Rails.application.routes.draw do
  namespace :webhook do
    resources :endpoints
  end
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  resources :products
  resources :webhook_endpoints
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "webhook/endpoints#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/webhook/observable.rb
module Webhook
  module Observable
    extend ActiveSupport::Concern

    included do
      after_commit on: :create do
        send_deliver_req :created
      end

      after_commit on: :update do
        send_deliver_req :updated
      end

      after_commit on: :destroy do
        send_deliver_req :destroyed
      end
    end

    def send_deliver_req(action)
      DeliverRequestService.call(event: format_event_name(action), payload: self.as_json)
    end

    def format_event_name(action)
      self.class.name.underscore + '.' + action.to_s
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
	include Webhook::Observable
end

app/models/webhook.rb
module Webhook
  def self.table_name_prefix
    "webhook_"
  end
end

app/models/webhook/endpoint.rb
module Webhook
  class Endpoint < ApplicationRecord
    
    # Associations
    has_many :event_requests, class_name: "Webhook::EventRequest", foreign_key: :webhook_endpoint_id, dependent: :destroy
    has_many :headers, class_name: "Webhook::Header", foreign_key: :webhook_endpoint_id, inverse_of: :webhook_endpoint, dependent: :destroy

    # Validations
    validates :url, presence: true, format: URI.regexp(%w(http https))
    validates :events, presence: true

    # Enums
    enum :status, { active: 'active', disable: 'disable'}

    # Callbacks
    after_update :update_event_requests_url, :update_event_requests_status

    accepts_nested_attributes_for :headers, reject_if: :all_blank, allow_destroy: true


    def self.for_event(events)
      where('events @> ARRAY[?]::varchar[]', Array(events))
    end

    def subscribed?(event)
      events.include? event
    end

    def events=(events)
      events = Array(events).map { |event| event.to_s }
      super(Webhook::Event::EVENT_TYPES & events)
    end

    def disable!
      update!(status: 'disable')
    end

    private

    def update_event_requests_url
      return unless saved_change_to_url?

      event_requests.active.update_all(url: url)
    end

    def update_event_requests_status
      event_requests.disable_not_for_events!(events)
    end
  end
end

app/models/webhook/event.rb
module Webhook
  class Event
    EVENT_TYPES = %w(
      product.created
      product.updated
      product.destroyed
    ).freeze
  end
end

app/models/webhook/event_request.rb
module Webhook
	class EventRequest < ApplicationRecord
		
		# Associations
		belongs_to :webhook_endpoint, class_name: "Webhook::Endpoint", foreign_key: :webhook_endpoint_id

		# Enums
		enum :status, { inprogress: 'inprogress', #While it is in inprogess
						success: 'success', # On successfull request
						failed: 'failed', # Failed due to any reason
						disable: 'disable'} # Disable requests no longer executed by worker

		# Scopes
		scope :active, -> {where.not(status: 'disable')}

		def success!
			update!(status: 'success')
		end

		def failed!
			update(status: 'failed')
		end

		def self.disable_not_for_events!(events) # event can be string(event) or array of strings(event)
			active.where.not(event: Array(events)).disable_all
		end

		def self.disable_for_events!(events)
			active.where(event: Array(events)).disable_all
		end

		private

		def self.disable_all
			update_all(status: 'disable', response: {message: "Subscription is removed for this event"})
		end
	end
end

app/models/webhook/header.rb
module Webhook
  class Header < ApplicationRecord

    # Validations
    validates_presence_of :key, :value

    # Associations
    belongs_to :webhook_endpoint, class_name: "Webhook::Endpoint", foreign_key: :webhook_endpoint_id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products
  def index
    @products = Product.all
  end

  # GET /products/1
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :price, :quantity)
    end
end

app/controllers/webhook/endpoints_controller.rb
module Webhook
  class EndpointsController < ApplicationController
    before_action :set_webhook_endpoint, only: %i[ show edit update destroy ]

    # GET /webhook/endpoints
    def index
      @webhook_endpoints = Webhook::Endpoint.all
    end

    # GET /webhook/endpoints/1
    def show
      @event_requests = @webhook_endpoint.event_requests.order(id: :DESC)
      @headers = @webhook_endpoint.headers
    end

    # GET /webhook/endpoints/new
    def new
      @webhook_endpoint = Webhook::Endpoint.new
      1.times do
        @webhook_endpoint.headers.build
      end
    end

    # GET /webhook/endpoints/1/edit
    def edit
      3.times do
        @webhook_endpoint.headers.build
      end
    end

    # POST /webhook/endpoints or /webhook/endpoints.json
    def create
      @webhook_endpoint = Webhook::Endpoint.new(webhook_endpoint_params)
      respond_to do |format|
        if @webhook_endpoint.save
          format.html { redirect_to webhook_endpoint_url(@webhook_endpoint), notice: "Endpoint was successfully created." }
        else
          format.html { render :new, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /webhook/endpoints/1
    def update
      respond_to do |format|
        if @webhook_endpoint.update(webhook_endpoint_params)
          format.html { redirect_to webhook_endpoint_url(@webhook_endpoint), notice: "Endpoint was successfully updated." }
        else
          format.html { render :edit, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /webhook/endpoints/1
    def destroy
      @webhook_endpoint.destroy

      respond_to do |format|
        format.html { redirect_to webhook_endpoints_url, notice: "Endpoint was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
    def set_webhook_endpoint
      @webhook_endpoint = Webhook::Endpoint.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def webhook_endpoint_params
      params.require(:webhook_endpoint).permit(:url, events: [], headers_attributes: [:id, :key, :value,:_destroy])
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/webhook/endpoints_helper.rb
module Webhook::EndpointsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Onwords</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <style type="text/css">
      table, th, tr, td {
        border: 1px solid black;
        border-collapse: collapse;
      }
    </style>
  </head>

  <body>
    <p style="color: green"><%= notice %></p>
    <ul>
      <li><%= link_to "Products", products_path %></li>
      <li><%= link_to "Endpoints", webhook_endpoints_path %></li>
    </ul>
    <hr/>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<tr id="<%= dom_id product %>">
  <td><%= index + 1 %></td>
  <td><%= product.name %></td>
  <td><%= product.price %></td>
  <td><%= product.quantity %></td>
  <td><%= link_to "View", product %></td>
</tr>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<h1>Products</h1>

<table id="products">
  <tr>
    <th>S.No</th>
    <th>Name</th>
    <th>Price</th>
    <th>Qantity</th>
    <th>Action</th>
  </tr>
  <% @products.each_with_index do |product, index| %>
    <%= render product, index: index %>
  <% end %>
</table>
<br/>
<%= link_to "New product", new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<div id="<%= dom_id @product %>">
  <p>
    <strong>Name:</strong>
    <%= @product.name %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= @product.price %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= @product.quantity %>
  </p>

</div>

<div>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>

  <%= button_to "Destroy this product", @product, method: :delete %>
</div>

app/views/webhook/endpoints/_endpoint.html.erb
<tr id="<%= dom_id endpoint %>">
    <td><%= index + 1 %></td>
    <td><%= endpoint.url %></td>
    <td><%= link_to "View", endpoint %>
</td>
</tr>

app/views/webhook/endpoints/_event_requests.html.erb
<h3>Event Requests: </h3>
<table id="webhook_endpoints">
  <tr>
    <th>S.No</th>
    <th>Event</th>
    <th>Payload</th>
    <th>Response</th>
    <th>Status</th>
  </tr>
  <% @event_requests.each_with_index do |event_request, index| %>
    <tr>
      <td><%= index + 1%></td>
      <td><%= event_request.event%></td>
      <td><%= event_request.payload%></td>
      <td><%= event_request.response%></td>
      <td><%= event_request.status.capitalize%></td>
    </tr>
  <% end %>
</table>

app/views/webhook/endpoints/_form.html.erb
<%= form_with(model: webhook_endpoint) do |form| %>
  <% if webhook_endpoint.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(webhook_endpoint.errors.count, "error") %> prohibited this webhook_endpoint from being saved:</h2>

      <ul>
        <% webhook_endpoint.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :url%>
    <%= form.text_field :url %>
  </div>

  <div>
    <h3>Select Events:</h3>
    <% Webhook::Event::EVENT_TYPES.each do |event_type| %>
      <%= form.check_box(:events, { :multiple => true }, event_type) %>
      <%= form.label :events, event_type,  value: event_type %>
    <% end %>
  </div>
  <br/>
  <br/>
  <h3>Add Custom Headers:</h3>
  <%= form.fields_for :headers do |header| %>
    <div>
      <%= header.label :key %>
      <%= header.text_field :key %>

      <%= header.label :value%>
      <%= header.text_field :value %>

      <%= header.label :_destroy %>
      <%= header.check_box :_destroy %>

    </div>
    <br/>
  <% end %>

  <%= form.submit %>
<% end %>

app/views/webhook/endpoints/_headers.html.erb
<h3>Custom Headers: </h3>
<table id="webhook_headers">
  <tr>
    <th>S.No</th>
    <th>Key</th>
    <th>Value</th>
   </tr>
  <% @headers.each_with_index do |header, index| %>
    <tr>
      <td><%= index + 1%></td>
      <td><%= header.key%></td>
      <td><%= header.value%></td>
    </tr>
  <% end %>
</table>

app/views/webhook/endpoints/edit.html.erb
<h1>Editing endpoint</h1>

<%= render "form", webhook_endpoint: @webhook_endpoint %>

<br>

<div>
  <%= link_to "Show this endpoint", @webhook_endpoint %> |
  <%= link_to "Back to endpoints", webhook_endpoints_path %>
</div>

app/views/webhook/endpoints/index.html.erb
<h1>Endpoints</h1>


<table id="webhook_endpoints">
  <tr>
    <th>S.No</th>
    <th>Url</th>
    <th>Actions</th>
  </tr>
  <% @webhook_endpoints.each_with_index do |webhook_endpoint, index| %>
    <%= render webhook_endpoint, index: index %>
  <% end %>
</table>


<br/>

<%= link_to "New webhook endpoint", new_webhook_endpoint_path %>

app/views/webhook/endpoints/new.html.erb
<h1>New endpoint</h1>

<%= render "form", webhook_endpoint: @webhook_endpoint %>

<br>

<div>
  <%= link_to "Back to endpoints", webhook_endpoints_path %>
</div>

app/views/webhook/endpoints/show.html.erb
<h3>URL: <%= @webhook_endpoint.url %></h3>
<p><strong>Events:</strong> <%= @webhook_endpoint.events.to_sentence %></p>

<div>
  <%= link_to "Edit", edit_webhook_endpoint_path(@webhook_endpoint) %> |
  <%= link_to "Back", webhook_endpoints_path %>
<br/>

  <%= button_to "Delete", @webhook_endpoint, method: :delete %>
</div>
<br/>
<%= render "headers" %>
<br/>
<%= render "event_requests" %>